### ISSUE TITLE
cp: target '/usr/bin/fleet' is not a directory

### ISSUE THREAD

**Issue by TonyLeeVT** [deeso/fleet-deployment#1]
Thank you for the install and configuration scripts.  However, the install.sh script tries to copy the fleet binaries to a directory that does not exist.

Line 76 of install.sh is:
`sudo cp tmp_fleet/linux/fleet* /usr/bin/fleet
`
But may need to be changed to:
`sudo cp tmp_fleet/linux/fleet* /usr/bin/
`

It will get rid of this error:
```
Saving to: ‘fleet_latest.zip’

fleet_latest.zip    100%[===================>]  81.85M  19.3MB/s    in 4.3s    

2019-05-08 17:52:33 (19.0 MB/s) - ‘fleet_latest.zip’ saved [85824832/85824832]

Archive:  fleet_latest.zip
   creating: tmp_fleet/linux/
  inflating: tmp_fleet/linux/fleetctl  
  inflating: tmp_fleet/linux/fleet   
**cp: target '/usr/bin/fleet' is not a directory**
Reading package lists... Done
```

**Comment by deeso** [comment]
thanks
